### ISSUE TITLE
Add support for GitHub as issue tracker

### ISSUE THREAD

**Issue by stopthatcow** [stopthatcow/zazu#20]
Support GitHub ticket creation and status

**Comment by aramnhammer** [comment]
This also needs to check if there is an upstream remote.

possible check in zazu/dev/commands.py under the ticket command we can check against...
`ctx.obj.repo.remotes`
which will return the remotes that the user should be able to pick from, or check if a ticket exists in.

**Comment by stopthatcow** [comment]
Done, see #26
